[package]
name = "nw-implant"
version.workspace = true
edition.workspace = true
description = "NaughtyWolf C2 implant beacon"

[dependencies]
nw-profile = { path = "../profile" }
tokio.workspace = true
serde.workspace = true
serde_json.workspace = true
tracing.workspace = true
anyhow.workspace = true
uuid.workspace = true
reqwest = { workspace = true, features = ["rustls-tls", "stream"] }
base64.workspace = true
rand.workspace = true
tracing-subscriber.workspace = true
sha2.workspace = true
hex.workspace = true
hostname = "0.4"
whoami = "1.6"
local-ip-address = "0.6"
chrono.workspace = true
sysinfo = "0.38.4"

[target.'cfg(unix)'.dependencies]
libc = "0.2"

[target.'cfg(windows)'.dependencies]
windows-sys = { version = "0.61", features = ["Win32_Storage_FileSystem"] }

[dev-dependencies]
nw-server = { path = "../server" }
tempfile.workspace = true
axum.workspace = true
